---
upload_path: "/img/content"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: "/admin123"
webhook_url: 
collections: 
