---
upload_path: "/img"
frontmatter_file_url_template: "/img"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections: 
