---
new_page_extension: md
auto_deploy: true
admin_path: "/admin123"
webhook_url: 
collections: 
upload_dir: img/content
public_path: "/img/content"
front_matter_path: "/img/content"
use_front_matter_path: false
file_template: ":filename:"
