---
upload_path: "/img/content"
frontmatter_file_url_template: "/img/content"
body_file_url_template: "/img/content"
new_page_extension: md
auto_deploy: true
admin_path: "/admin123"
webhook_url: 
collections: 
