---
label: default
hide_body: false
fields:
- type: text
  label: title
  name: title
  config:
    required: true
- type: select
  config:
    source:
      type: simple
    options:
    - page-menu-left
    - page
    required: true
  label: layout
  name: layout
  default: page-menu-left
- type: text
  name: keywords
  label: keywords
  config:
    required: true
- type: text
  name: author
  label: author
- type: file
  name: mainImageUrl
  label: mainImageUrl
  config:
    maxSize: '3'
- type: text
  name: mainImageWidth
  label: mainImageWidth
  default: 100%
- type: text
  name: mainImageHeight
  label: mainImageHeight
- type: text
  name: pinterest_url
  label: Pinterest url
pages:
- aanbod.html
- kozijnen.md
- aanbouw_verbouw.md
- duurzaam.md
- test7.md
- badkamers.md
- veranda.md
- schoonheid.md
- sanitair.md
- LEDverlichting.md
- kwaliteit.md
- serre.md
- zonwering/index.html
- deuren.md
- tegels.md
- dakkapellen.md
- contact.html
- schuifpuien.md
- showroom.md
- vloerverwarming.md
- _uploads/tegels.md
