---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  label: title
  name: title
  config:
    required: true
- type: select
  config:
    source:
      type: simple
    options:
    - page-menu-left
    - page
    required: true
  label: layout
  name: layout
  default: page-menu-left
- type: text
  name: keywords
  label: keywords
  config:
    required: true
- type: text
  name: author
  label: author
- type: file
  name: mainImageUrl
  label: mainImageUrl
  config:
    maxSize: '3'
- type: text
  name: mainImageWidth
  label: mainImageWidth
  default: 100%
- type: text
  name: mainImageHeight
  label: mainImageHeight
pages:
- dakkapellen.md
- showroom.md
- serre.md
- deuren.md
- sanitair.md
- schoonheid.md
- contact.html
- veranda.md
- contact2.html
- schuifpuien.md
- aanbod.html
- badkamers.md
- tegels.md
- duurzaam.md
- kozijnen.md
- aanbouw_verbouw.md
- _uploads/tegels.md
- test7.md
- test5.md
